import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  // const hello = trpc.proxy.example.hello.useQuery({ text: "from tRPC" });
  const words = trpc.proxy.vocab.learnOrder.useQuery({
    words: ['食べる', '失礼', '陰謀論', '一期一会'],
    weights: {
      animeJDrama: 1,
      bccwj: 1,
      innocent: 1,
      kokugojiten: 1,
      narou: 1,
      netflix: 1,
      novels: 1,
      vn: 1,
      wikipedia: 1,
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>
          Create <span>T3</span> App
        </h1>

        <div>
          <h3>This stack uses:</h3>
          <ul>
            <li>
              <a href='https://nextjs.org' target='_blank' rel='noreferrer'>
                Next.js
              </a>
            </li>
            <li>
              <a href='https://trpc.io' target='_blank' rel='noreferrer'>
                tRPC
              </a>
            </li>
            <li>
              <a
                href='https://typescriptlang.org'
                target='_blank'
                rel='noreferrer'
              >
                TypeScript
              </a>
            </li>
          </ul>

          <div>
            {words.data ? (
              <p>{JSON.stringify(words.data, null, 2)}</p>
            ) : (
              <p>Loading..</p>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
